### ISSUE TITLE
Module - 3 Missing import in Layout.spec.js

### ISSUE THREAD

**Issue by judit-nahaj** [Idea-Pool/js-webinar#63]
In the unit test of the Layout class Element is used (line 69), but it is not imported.
This causes the related tests to fail even though the class has been implemented correctly.

File:
https://github.com/Idea-Pool/js-webinar/blob/master/module-3/test/pop/Layout.spec.js

**Comment by szikszail** [comment]
Fixed in https://github.com/Idea-Pool/js-webinar/commit/60b88178212a318565405c795fc4db2cd6d2e8ab
